### ISSUE TITLE
Bullets and Express Routes Missing from Caltrain

### ISSUE THREAD

**Issue by DavidOry** [BayAreaMetro/travel-model-two-networks#10]
fyi @i-am-sijia 
I will look into this with your latest updates.

**Comment by DavidOry** [comment]
@i-am-sijia 
It looks like Caltrain is grabbing the weekend service. Can you please update to grab the `CT-14OCT-Combo-Weekday-01` service id? (It looks like they were running a bus bridge on the weekday, so it probably had a lot of trips in it).

**Comment by i-am-sijia** [comment]
@DavidOry yep, found the same.  I will change it to weekday service.  Generally, should I change it for all agencies to exclude weekends?

**Comment by DavidOry** [comment]
> @DavidOry yep, found the same. I will change it to weekday service. Generally, should I change it for all agencies to exclude weekends?

Yes. The Partridge approach of grabbing the busiest day should work fine in most all cases. All the other agencies looked fine.

**Comment by i-am-sijia** [comment]
![image](https://user-images.githubusercontent.com/28812722/93114594-bde35980-f688-11ea-92d5-bcf3924c0332.png)
