### ISSUE TITLE
VTA Routes Have Incorrect Stop Sequence

### ISSUE THREAD

**Issue by DavidOry** [BayAreaMetro/travel-model-two-networks#11]
Here's an example

<img width="1157" alt="Screen Shot 2020-09-11 at 2 22 15 PM" src="https://user-images.githubusercontent.com/6684315/92959724-53d57500-f43a-11ea-9e9c-2210c580ed2e.png">

**Comment by i-am-sijia** [comment]
VTA's stop times data is not sorted by `stop_sequence`.  I will sort it before routing.  Thanks for catching this.

**Comment by i-am-sijia** [comment]
![image](https://user-images.githubusercontent.com/28812722/93114355-82488f80-f688-11ea-9705-f067c3cc77f4.png)

**Comment by i-am-sijia** [comment]
After updating shortest path method:

![image](https://user-images.githubusercontent.com/28812722/93148304-6b725f00-f6c1-11ea-91bb-26cf7ec4a45f.png)
