### ISSUE TITLE
A bus only link sharing AB nodes with others

### ISSUE THREAD

**Issue by i-am-sijia** [BayAreaMetro/travel-model-two-networks#16]
@DavidOry One of the bus only links `shstReferenceId = cb711b2cd73ebb6ac0548350ae9f226e` identified in [this bus only project card](https://github.com/BayAreaMetro/travel-model-two-networks/blob/develop/project_cards/year_2015_bus_only_transbay_terminal_ramps.yml) no longer exists after cleaning up links sharing the same AB nodes.

![image](https://user-images.githubusercontent.com/28812722/94053965-fb429800-fda8-11ea-9fb7-023814ff9f3a.png)

**Comment by DavidOry** [comment]
Thanks for letting me know. Should not be an issue.
