### ISSUE TITLE
Make Transit Project Card Notebook

### ISSUE THREAD

**Issue by DavidOry** [BayAreaMetro/travel-model-two-networks#26]
@i-am-sijia: can you please help me get this [notebook](https://github.com/BayAreaMetro/travel-model-two-networks/blob/develop/notebooks/make-transit-project-cards.ipynb) up and running? I'm having two problems:

1. The `lasso_base_dir` is not being found from the parameters object. This may be user error, but I cannot figure out the problem.
2. The code is expecting `SHORTNAME` strings to have quotes around them, but the input `.lin` file does not, e.g., `SHORTNAME=G`. Do we need to change the write statement to add quotes around strings?

**Comment by i-am-sijia** [comment]
@DavidOry This has been fixed.  The agency-specific .lin files on Box are updated to have quotes around `SHORTNAME`.
