### ISSUE TITLE
Managed Lane Error: I-80 near Bay Bridge

### ISSUE THREAD

**Issue by DavidOry** [BayAreaMetro/travel-model-two-networks#28]
I-80 into Bay Bridge: Links 2540517-2554289, 2554289-2531339 should be HOV lanes (HOV 3+) on peak periods. There should be an HOV 3+ between nodes 2531339 and 7075013. The HOV 3+ lane ending in node 7019445 should be extended to 7047110.

fyi @bespinmtc, @i-am-sijia

**Comment by ychtw** [comment]
1. still need to add shstReferenceId for model_link_id: 3033149, 3103371
2. question: looks like links 2540517-2554289, 2554289-2531339 are set to be HOV 3+ on all time periods now. Should I modify the corresponding project card `year_2015_managed_lane_i80_ramp_to_bay_bridge.yml` to set these links as HOV 3+ only on peak periods?

**Comment by DavidOry** [comment]
Re: 2. Yes, peak periods only.

**Comment by i-am-sijia** [comment]
> looks like links 2540517-2554289, 2554289-2531339 are set to be HOV 3+ on all time periods now. Should I modify the corresponding project card year_2015_managed_lane_i80_ramp_to_bay_bridge.yml to set these links as HOV 3+ only on peak periods?

This [project card](https://github.com/BayAreaMetro/travel-model-two-networks/blob/d09e486f4b1e8138dd72102c73cbd247c4bc5747/project_cards/year_2015_managed_lane_i80_ramp_to_bay_bridge.yml) does not run, it has `Roadway Property Change` category, but has `Parallel Managed Lane` structure.  From the conversation, sounds to me it should just be a simple `useclass` change by time of day. @ychtw can you confirm it should just be a useclass change?  If so, I can make the correction.

**Comment by ychtw** [comment]
@i-am-sijia yes, it should just be `useclass` change by time of day. Thank you!
