### ISSUE TITLE
Managed Lane Error: I-80 Gaps

### ISSUE THREAD

**Issue by DavidOry** [BayAreaMetro/travel-model-two-networks#29]
2-      I-80: Gap in HOV lane between nodes 7568461 and 7507878 (parallel to link 3068461-3007878)
3-      I-80 there is a gap in HOV lane between nodes 7535195 and 7528990.
4-      I-80: gap in HOV lane between nodes 7507785 and 7551622 on I-80 (missing HOV link parallel to link 3007785-3051622).

fyi @bespinmtc, @i-am-sijia

**Comment by ychtw** [comment]
still need to add shstReferenceId for model_link_id: 4092393, 4007752, 4052891
