### ISSUE TITLE
Put Build Pipeline all in Docker

### ISSUE THREAD

**Issue by DavidOry** [BayAreaMetro/travel-model-two-networks#3]
Given the current use of Docker to run the `node.js` components, it would be nice to create a single Docker container with both the `node` and `python` components it needs, and then run the entire pipeline via Docker.

**Comment by lmz** [comment]
We've been having some difficulties with Docker on windows (cc @yuqiww @FlaviaTsang @natchison-mtc) so would not recommend doing this at this time.  Closing for now.
