### ISSUE TITLE
Managed Lane Error: SR12

### ISSUE THREAD

**Issue by DavidOry** [BayAreaMetro/travel-model-two-networks#30]
Should this 2-way link 3522575 – 3534696 on SR-12 be a collector? It connects a freeway with an expressway (this is not a managed lane).

fyi @bespinmtc, @i-am-sijia

**Comment by ychtw** [comment]
This does not fall in any project cards. 
It looks more like a confirmation whether link 3522575–3534696 should indeed be a collector (FT=6), not some other higher facility type. I guess the concern is whether this will create unwanted bottle neck between freeway and expressway it connects to.  Same for link 3534696-3513625 right next to it.

**Comment by DavidOry** [comment]
@ychtw
Can you please post an image here of the link?

**Comment by ychtw** [comment]
![SR12 (issue #30)](https://user-images.githubusercontent.com/38272089/132384352-660bab57-4a9d-483a-8df9-d2e5eaa26297.jpeg)

link 3522575–3534696 and 3534696-3513625 are marked in green in the middle.
Expressway (FT=2) on the left (marked in orange)
Freeway (FT=1) on the right (marked in red)

**Comment by bespinmtc** [comment]
@DavidOry Regarding the freeway segment on this I-80/SR-12 interchange, should that be a freeway or a ramp? For the highway reliability calculations we will need to code the freeway interchange locations in the network. On TM2 we don't have the freeway-to-freeway facility type that would help with this calculation. But I see that in some interchanges the ramps connecting the freeways are coded as FT=3 (ramps) and in other as FT=1 (freeways) as in this example. Which one should it be?

**Comment by DavidOry** [comment]
@bespinmtc:  I think this should be a ramp. The interchange at Red Top Road is pretty dicey, which will require people to slow down. @ychtw: please add the links in both directions to the "should be ramp" card [here](https://github.com/BayAreaMetro/travel-model-two-networks/blob/develop/project_cards/year_2015_roadway_property_change_should_be_ramp_lanes_correct.yml) and then add the links with incorrect lanes to the appropriate "should be X lanes" card.
