### ISSUE TITLE
Managed Lane Error: Lawrence Expressway

### ISSUE THREAD

**Issue by DavidOry** [BayAreaMetro/travel-model-two-networks#34]
12-   According to 511.org, the Lawrence Expressway HOV starts at 237. The segment from US-1010 to SR-237 does not have a HOV lane.

fyi @bespinmtc, @i-am-sijia

**Comment by ychtw** [comment]
1. still need to add shstReferenceId
2. maybe should rename project cards as: 
    - `year_2015_managed_lane_lawrence_expresswayn_i280_to_sr237.yml`
    - `year_2015_managed_lane_lawrence_expressways_sr237_to_i280.yml`

**Comment by DavidOry** [comment]
Yes, please update names.
