### ISSUE TITLE
Managed Lane Error: Montague Expressway

### ISSUE THREAD

**Issue by DavidOry** [BayAreaMetro/travel-model-two-networks#36]
15-   Montague Expressway is HOV on the AM Peak WB and PM peak EB. (add to document)

fyi @bespinmtc, @i-am-sijia

**Comment by ychtw** [comment]
might need new segment_id so that id for Montague Expressway is different from San Tomas Expressway?

**Comment by DavidOry** [comment]
Yes, please make sure `segment_id` is unique.
