### ISSUE TITLE
Managed Lane Error: US-101 in Marin

### ISSUE THREAD

**Issue by DavidOry** [BayAreaMetro/travel-model-two-networks#37]
16-   According to 511, US-101 between Marin City and Novato is  HOV only Southbound at the AM peak and HOV only Northbound in the PM peak.

@bespinmtc, @i-am-sijia

**Comment by ychtw** [comment]
project card name & description seems to be off from where these links are:
- NB: `year_2015_managed_lane_us101n_north_petaluma_to_south_healdsburg.yml`
- SB:  `year_2015_managed_lane_us101s_south_healdsburg_to_north_petaluma.yml`

Both Petaluma and Healdsburg are further north. Links included in these project cards are only from north of Marin City to Novato.

**Comment by DavidOry** [comment]
Yes, please update the name.
