### ISSUE TITLE
Fix fare system for Alameda/Oakland and South San Francisco ferries

### ISSUE THREAD

**Issue by bespinmtc** [BayAreaMetro/travel-model-two-networks#43]
The fare for the Alameda/ Oakland ferry is $6.40. The faresystem for those ferries in v12 is 27, and that faresystem has a flat fare of $7.40 ($6.86 in 2010 dollars). For the South San Francisco ferries, the fare to the East Bay and SF is $7.40. The faresystems for those ferries are 30 and 31. But the flat fare on those faresystems is $6.40 ($5.93 in 2010 dollars). We just need to switch the faresystems for both ferries.

**Comment by i-am-sijia** [comment]
[This can be closed.](https://app.asana.com/0/0/1201003210087638/1201090890321915/f)
