### ISSUE TITLE
Fix fare system for Tri-Delta line 300

### ISSUE THREAD

**Issue by bespinmtc** [BayAreaMetro/travel-model-two-networks#44]
The TriDelta line 300 has a fare of $2.50. This corresponds to faresystem 35. But the line was coded with faresystem 36 ($2.00). Change the faresystem of line 300 to 35.

**Comment by i-am-sijia** [comment]
[This can be closed.](https://app.asana.com/0/0/1201003210087638/1201090890321915/f)
