### ISSUE TITLE
Freeway names are not useful, missing route num

### ISSUE THREAD

**Issue by lmz** [BayAreaMetro/travel-model-two-networks#55]
The `name` value for freeway links are the less known wordy version, like 'James Lick Freeway', 'Bayshore Freeway', etc.
Either the name or other field(s) should include the shield number and direction, e.g. 80 Northbound

**Comment by yuqiww** [comment]
This issue is resolve by [methods.determine_road_name()](https://github.com/BayAreaMetro/travel-model-two-networks/blob/dcf130644c899e051b9b27e681b84e3b598af939/notebooks/pipeline/methods.py#L3703).
